"""add unique constraint to role name

Revision ID: 2a3216bc7f69
Revises: c078267d2bbf
Create Date: 2026-09-26 18:47:36.808256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3216bc7f69'
down_revision = 'c078267d2bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_role_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_name', type_='unique')

    # ### end Alembic commands ###
